# Generated by Django 3.2.8 on 2021-10-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
    ]
