# Generated by Django 3.2.8 on 2021-10-29 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_img_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
